### PR TITLE
intro section updated

### PR DESCRIPTION
**Pull request by rwoll**
@ericthewry I'll be making all my edits here, some of which are being rebuilt from the old repository since I needed a bit more proofreading anyways.

### CODE REVIEW

**Comment by ericthewry** [comment]
Sounds good:)

**Comment by rwoll** [comment]
@ericthewry FYI: Some of the Jekyll syntax isn't going to compile on GitHub for the syntax highlighting in the `.md`, but if you run the site locally, you will see the appropriate rendering.

* * *
In jekyll to syntax highlight a code block, use the following syntax:
```
{% highlight bash %}
cd /some/directory/
{% endhighlight %}
```
> If a jekyll code block is in the middle of a numeric list of a normal markdown file, it will break the numbering. :(

**Comment by rwoll** [comment]
@ericthewry I'm going to pause with my work on this until you have a chance to review tomorrow. I think it's a good start, but there is definitely a lot I need to clarify, add, and proofread.

One thing that I'm struggling to decide is the amount of explanation for each step especially those involving git commands. I think we need to find a proper balance between being concise (as not to overwhelm with technical jargon), but we want to explain what is going on behind the scenes so students learn some of the git concepts. Perhaps we should include more of an explanation and then trim it down later based on professor and student feedback--just a thought.

**Comment by ericthewry** [comment]
Looks good:)

**Pull request merged**
